Toko-Online-Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
  return view('welcome');
});

Route::get('/clear-cache', function () {
  Artisan::call('config:clear');
  Artisan::call('cache:clear');
  Artisan::call('config:cache');
  return 'DONE';
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
  Route::middleware(['role'])->group(function () {
    Route::resource('/merek', 'MerekController');
    Route::resource('/order', 'OrderController');
    Route::get('/order/tampil_cancel', 'OrderController@tampil_cancel')->name('order.tampil_cancel');
    Route::get('/order/tampil_bayar', 'OrderController@tampil_bayar')->name('order.tampil_bayar');
    Route::get('/order/tampil_pending', 'OrderController@tampil_pending')->name('order.tampil_pending');
    Route::resource('/akun', 'AkunController');
    Route::resource('/mobil', 'MobilController');
    Route::get('/create/mobil', 'MobilController@create')->name('create.mobil');
    Route::get('/mobil/tampil_hapus', 'MobilController@tampil_hapus')->name('mobil.tampil_hapus');
    Route::get('/mobil/restore/{id}', 'MobilController@restore')->name('mobil.restore');
    Route::delete('/mobil/kill/{id}', 'MobilController@kill')->name('mobil.kill');
  });

  Route::get('/', 'MobilController@home')->name('home');
  Route::get('/home', 'MobilController@home')->name('home');
  Route::get('/favorite', 'MobilController@favorite')->name('favorite');
  Route::get('/like/{id}', 'MobilController@like')->name('like');
  Route::get('/unlike/{id}', 'MobilController@unlike')->name('unlike');
  Route::get('/cart', 'MobilController@cart')->name('cart');
  Route::get('/add-to-cart/{id}', 'MobilController@addToCart')->name('add-to-cart');
  Route::get('/mobil/{id}', 'MobilController@show')->name('mobil.show');
  Route::get('/profil/{id}', 'AkunController@profil')->name('profil');
  Route::get('/edit_profil/{id}', 'AkunController@edit_profil')->name('edit_profil');
  Route::post('/akun/simpan/{id}', 'AkunController@simpan')->name('akun.simpan');
  Route::patch('/update_cart', 'MobilController@update_cart')->name('update_cart');
  Route::delete('/remove', 'MobilController@remove')->name('remove');
  Route::delete('/order/{id}', 'OrderController@destroy')->name('order.destroy');
  Route::get('/cekout', 'MobilController@cekout')->name('cekout');
  Route::get('/category/{id}', 'MobilController@category')->name('category');
  Route::get('/history', 'OrderController@history')->name('history');
  Route::get('/pembayaran/success', 'OrderController@success')->name('pembayaran.success');
  Route::get('/pembayaran/{id}', 'OrderController@pembayaran')->name('pembayaran');
  Route::patch('/proses_pembayaran/{id}', 'OrderController@proses_pembayaran')->name('proses_pembayaran');
  Route::post('/proses_cekout/{id}', 'MobilController@proses_cekout')->name('proses_cekout');
});

Toko-Online-Laravel/app/Http/Controllers/AkunController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Mobil;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class AkunController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $user = User::paginate(10);
    return view('admin.akun.index', compact('user'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('admin.akun.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'name' => 'required',
      'role' => 'required',
      'email' => 'required',
      'password' => 'required|min:8',
    ]);

    if ($request->has('gambar') == true) {
      $gambar = $request->gambar;
      $new_gambar = time() . "_" . $gambar->getClientOriginalName();
      $gambar->move('uploads/akun/', $new_gambar);
      User::create([
        'name' => $request->name,
        'role' => $request->role,
        'gambar' => 'uploads/akun/' . $new_gambar,
        'email' => $request->email,
        'password' => Hash::make($request->password),
      ]);
    } else {
      User::create([
        'name' => $request->name,
        'role' => $request->role,
        'email' => $request->email,
        'password' => Hash::make($request->password),
      ]);
    }


    return redirect()->back()->with('success', 'User Baru Berhasil Disimpan');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    $user = Mobil::findorfail($id);
    return view('admin.show', compact('user'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $user = User::findorfail($id);
    return view('admin.akun.edit', compact('user'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $this->validate($request, [
      'name' => 'required',
      'role' => 'required',
      'email' => 'required',
      'address' => 'required',
      'kelurahan' => 'required',
      'kabupaten' => 'required',
      'kecamatan' => 'required',
      'provinsi' => 'required',
      'telepon' => 'required',
    ]);
    if ($request->tgl_lahir) {
      $request->tgl_lahir = date('Y-m-d', strtotime($request->tgl_lahir));
    }

    $user = User::findorfail($id);

    if ($request->gambar == true) {
      $gambar = $request->gambar;
      $new_gambar = time() . "_" . $gambar->getClientOriginalName();
      $gambar->move('uploads/akun/', $new_gambar);

      if ($request->gambar && $request->pekerjaan == true) {

        if ($request->gambar && $request->pekerjaan && $request->tgl_lahir == true) {

          if ($request->gambar && $request->pekerjaan && $request->tgl_lahir && $request->password == true) {
            $user_data = [
              'name' => $request->name,
              'role' => $request->role,
              'email' => $request->email,
              'address' => $request->address,
              'kelurahan' => $request->kelurahan,
              'kabupaten' => $request->kabupaten,
              'kecamatan' => $request->kecamatan,
              'provinsi' => $request->provinsi,
              'telepon' => $request->telepon,
              'pekerjaan' => $request->pekerjaan,
              'tanggal_lahir' => $request->tgl_lahir,
              'password' => Hash::make($request->password),
              'gambar' => 'uploads/akun/' . $new_gambar,
            ];
          } else {
            $user_data = [
              'name' => $request->name,
              'role' => $request->role,
              'email' => $request->email,
              'address' => $request->address,
              'kelurahan' => $request->kelurahan,
              'kabupaten' => $request->kabupaten,
              'kecamatan' => $request->kecamatan,
              'provinsi' => $request->provinsi,
              'telepon' => $request->telepon,
              'pekerjaan' => $request->pekerjaan,
              'tanggal_lahir' => $request->tgl_lahir,
              'gambar' => 'uploads/akun/' . $new_gambar,
            ];
          }
        } elseif ($request->gambar && $request->pekerjaan && $request->password == true) {
          $user_data = [
            'name' => $request->name,
            'role' => $request->role,
            'email' => $request->email,
            'address' => $request->address,
            'kelurahan' => $request->kelurahan,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'provinsi' => $request->provinsi,
            'telepon' => $request->telepon,
            'pekerjaan' => $request->pekerjaan,
            'password' => Hash::make($request->password),
            'gambar' => 'uploads/akun/' . $new_gambar,
          ];
        } else {
          $user_data = [
            'name' => $request->name,
            'role' => $request->role,
            'email' => $request->email,
            'address' => $request->address,
            'kelurahan' => $request->kelurahan,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'provinsi' => $request->provinsi,
            'telepon' => $request->telepon,
            'pekerjaan' => $request->pekerjaan,
            'gambar' => 'uploads/akun/' . $new_gambar,
          ];
        }
      } elseif ($request->gambar && $request->tgl_lahir == true) {

        if ($request->gambar && $request->tgl_lahir && $request->password == true) {
          $user_data = [
            'name' => $request->name,
            'role' => $request->role,
            'email' => $request->email,
            'address' => $request->address,
            'kelurahan' => $request->kelurahan,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'provinsi' => $request->provinsi,
            'telepon' => $request->telepon,
            'tanggal_lahir' => $request->tgl_lahir,
            'password' => Hash::make($request->password),
            'gambar' => 'uploads/akun/' . $new_gambar,
          ];
        } else {
          $user_data = [
            'name' => $request->name,
            'role' => $request->role,
            'email' => $request->email,
            'address' => $request->address,
            'kelurahan' => $request->kelurahan,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'provinsi' => $request->provinsi,
            'telepon' => $request->telepon,
            'tanggal_lahir' => $request->tgl_lahir,
            'gambar' => 'uploads/akun/' . $new_gambar,
          ];
        }
      } elseif ($request->gambar && $request->password == true) {
        $user_data = [
          'name' => $request->name,
          'role' => $request->role,
          'email' => $request->email,
          'address' => $request->address,
          'kelurahan' => $request->kelurahan,
          'kabupaten' => $request->kabupaten,
          'kecamatan' => $request->kecamatan,
          'provinsi' => $request->provinsi,
          'telepon' => $request->telepon,
          'password' => Hash::make($request->password),
          'gambar' => 'uploads/akun/' . $new_gambar,
        ];
      } else {
        $user_data = [
          'name' => $request->name,
          'role' => $request->role,
          'email' => $request->email,
          'address' => $request->address,
          'kelurahan' => $request->kelurahan,
          'kabupaten' => $request->kabupaten,
          'kecamatan' => $request->kecamatan,
          'provinsi' => $request->provinsi,
          'telepon' => $request->telepon,
          'gambar' => 'uploads/akun/' . $new_gambar,
        ];
      }
    } elseif ($request->pekerjaan == true) {

      if ($request->pekerjaan && $request->tgl_lahir == true) {

        if ($request->pekerjaan && $request->tgl_lahir && $request->password == true) {
          $user_data = [
            'name' => $request->name,
            'role' => $request->role,
            'email' => $request->email,
            'address' => $request->address,
            'kelurahan' => $request->kelurahan,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'provinsi' => $request->provinsi,
            'telepon' => $request->telepon,
            'tanggal_lahir' => $request->tgl_lahir,
            'password' => Hash::make($request->password),
            'pekerjaan' => $request->pekerjaan,
          ];
        } else {
          $user_data = [
            'name' => $request->name,
            'role' => $request->role,
            'email' => $request->email,
            'address' => $request->address,
            'kelurahan' => $request->kelurahan,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'provinsi' => $request->provinsi,
            'telepon' => $request->telepon,
            'tanggal_lahir' => $request->tgl_lahir,
            'pekerjaan' => $request->pekerjaan,
          ];
        }
      } elseif ($request->pekerjaan && $request->password == true) {
        $user_data = [
          'name' => $request->name,
          'role' => $request->role,
          'email' => $request->email,
          'address' => $request->address,
          'kelurahan' => $request->kelurahan,
          'kabupaten' => $request->kabupaten,
          'kecamatan' => $request->kecamatan,

Toko-Online-Laravel/resources/views/admin/akun/create.blade.php
@extends('template_backend.home')
@section('halaman', 'Tambah Akun')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <form action="{{ route('akun.store') }}" class="bg-white shadow-sm p-3" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="name">Name</label>
          <input class="form-control" placeholder="Full Name" type="text" name="name" id="name" autocomplete="off">
        </div>
        <div class="form-group">
          <label for="name">Roles</label><br>
          <input type="radio" name="role" id="admin" value="admin">
          <label for="admin">Admin</label>&nbsp;&nbsp;&nbsp;
          <input type="radio" name="role" id="member" value="member">
          <label for="member">Member</label>
        </div>
        <div class="form-group">
          <label for="exampleInputFile">Foto Profil</label>
          <div class="file-upload-inner ts-forms">
              <div class="input prepend-big-btn">
                  <label class="icon-right" for="prepend-big-btn">
                      <i class="fa fa-download"></i>
                  </label>
                  <div class="file-button">
                      Browse
                      <input type="file" name="gambar" onchange="document.getElementById('prepend-big-btn').value = this.value;">
                  </div>
                  <input type="text" id="prepend-big-btn" name="gambar" placeholder="no file selected">
              </div>
          </div>
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input class="form-control" placeholder="Email@gamil.com" type="email" name="email" id="email" autocomplete="off">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input class="form-control" placeholder="Password" type="password" name="password" id="password" autocomplete="off">
        </div>

        <div class="form-group">
          <button class="btn btn-primary btn-block">Simpan Akun</button>
        </div>
      </form>
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/akun/edit.blade.php
@extends('template_backend.home')
@section('halaman', 'Edit Akun')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <form action="{{ route('akun.update', $user->id) }}" class="bg-white shadow-sm p-3" method="post" enctype="multipart/form-data">
        @csrf
        @method('patch')
        <div class="form-group">
          <label>Username</label>
          <input type="text" class="form-control" name="name" value="{{ $user->name }}" autocomplete="off">
        </div>
        <div class="form-group">
          <label>Email</label>
          <input type="text" value="{{ $user->email }}" autocomplete="off" name="email" class="form-control">
        </div>
        @if ($user->pekerjaan)
          <div class="form-group">
            <label>Pekerjaan</label>
            <input type="text" value="{{ $user->pekerjaan }}" autocomplete="off" name="pekerjaan" class="form-control">
          </div>
        @else
          <div class="form-group">
            <label>Pekerjaan</label>
            <input type="text" placeholder="Pekerjaan" autocomplete="off" name="pekerjaan" class="form-control">
          </div>
        @endif
        <div class="form-group">
          <label for="name">Roles</label><br>
          <input type="radio" name="role" id="admin" value="admin">
          <label for="admin">Admin</label>&nbsp;&nbsp;&nbsp;
          <input type="radio" name="role" id="member" value="member">
          <label for="member">Member</label>
        </div>
        @if ($user->tanggal_lahir)
          <div class="form-group data-custon-pick" id="data_3">
            <label><h6>Tanggal Lahir</h6></label>
            <div class="input-group date">
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
              <input type="text" name="tgl_lahir" class="form-control" value="{{ date('m/d/Y', strtotime($user->tanggal_lahir)) }}">
            </div>
          </div>
        @else
          <div class="form-group data-custon-pick" id="data_3">
            <label><h6>Tanggal Lahir</h6></label>
            <div class="input-group date">
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
              <input type="text" name="tgl_lahir" class="form-control" value="22/11/2000">
            </div>
          </div>
        @endif
        <div class="form-group">
          <div class="row">
            <div class="col-md-12">
              @if($user->address)
                <div class="form-group">
                  <label>Alamat</label>
                  <input type="text" class="form-control" name="address" value="{{ $user->address }}">
                </div>
              @else
                <div class="form-group">
                  <label>Alamat</label>
                  <input type="text" class="form-control" name="address" placeholder="Alamat">
                </div>
              @endif
            </div>
            <div class="col-md-6">
              @if($user->kelurahan)
                <div class="form-group">
                  <label>Kelurahan</label>
                  <input type="text" class="form-control" name="kelurahan" value="{{ $user->kelurahan }}">
                </div>
              @else
                <div class="form-group">
                  <label>Kelurahan</label>
                  <input type="text" class="form-control" name="kelurahan" placeholder="Kelurahan">
                </div>
              @endif
              @if($user->kabupaten)
                <div class="form-group">
                  <label>Kabupaten</label>
                  <input type="text" class="form-control" name="kabupaten" value="{{ $user->kabupaten }}">
                </div>
              @else
                <div class="form-group">
                  <label>Kabupaten</label>
                  <input type="text" class="form-control" name="kabupaten" placeholder="Kabupaten">
                </div>
              @endif
            </div>
            <div class="col-md-6">
              @if($user->kecamatan)
                <div class="form-group">
                  <label>Kecamatan</label>
                  <input type="text" class="form-control" name="kecamatan" value="{{ $user->kecamatan }}">
                </div>
              @else
                <div class="form-group">
                  <label>Kecamatan</label>
                  <input type="text" class="form-control" name="kecamatan" placeholder="Kecamatan">
                </div>
              @endif
              @if($user->provinsi)
                <div class="form-group">
                  <label>Provinsi</label>
                  <input type="text" class="form-control" name="provinsi" value="{{ $user->provinsi }}">
                </div>
              @else
                <div class="form-group">
                  <label>Provinsi</label>
                  <input type="text" class="form-control" name="provinsi" placeholder="Provinsi">
                </div>
              @endif
            </div>
          </div>
        </div>
        @if($user->telepon)
          <div class="form-group">
            <label>Nomor Telepon</label>
            <input type="text" class="form-control" name="telepon" value="{{ $user->telepon }}">
          </div>
        @else
          <div class="form-group">
            <label>Nomor Telepon</label>
            <input type="text" class="form-control" name="telepon" placeholder="+62 8xx xxxx xxxx">
          </div>
        @endif
        <div class="form-group">
          <label>Password</label>
          <input class="form-control" placeholder="Password" type="password" name="password" autocomplete="off">
        </div>
        <div class="form-group">
          <label for="exampleInputFile">Foto</label>
          <div class="file-upload-inner ts-forms">
            <div class="input prepend-big-btn">
              <label class="icon-right" for="prepend-big-btn">
                <i class="fa fa-download"></i>
              </label>
              <div class="file-button">
                Browse
                <input type="file" name="gambar" onchange="document.getElementById('prepend-big-btn').value = this.value;">
              </div>
              <input type="text" id="prepend-big-btn" name="gambar" placeholder="no file selected">
            </div>
          </div>
        </div><br>

        <div class="form-group">
          <button class="btn btn-primary btn-block">Simpan Perubahan</button>
        </div>
      </form>
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/akun/index.blade.php
@extends('template_backend.home')
@section('halaman', 'List Akun')
@section('content')
  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <a href="{{ route('akun.create') }}" class="btn btn-primary btn-sm mb-2">Tambah User</a><br><br>
      <table class="table table-striped table-hover table-sm table-bordered">
        <tr>
          <th>Id</th>
          <th>Nama</th>
          <th>Roles</th>
          <th>Email</th>
          <th>Alamat</th>
          <th>Thumbnail</th>
          <th>Action</th>
        </tr>
        @foreach ($user as $result => $d)
          <tr>
            <td>{{ $result + $user->firstitem() }}</td>
            <td>{{ $d->name }}</td>
            <td>{{ $d->role }}</td>
            <td>{{ $d->email }}</td>
            <td>
              @if($d->address && $d->kelurahan && $d->kecamatan && $d->kabupaten && $d->provinsi)
                {{ $d->address }}, {{ $d->kelurahan }}, {{ $d->kecamatan }}, {{ $d->kabupaten }}, {{ $d->provinsi }}
              @else
                N/A
              @endif
            </td>
            <td>
              @if($d->gambar)
                <img src="{{ asset( $d->gambar ) }}" class="img-fluid" width="100" alt="">
              @else
                N/A
              @endif
            </td>
            <td>
              <form action="{{ route('akun.destroy', $d->id) }}" method="post">
                @csrf
                @method('delete')
                <a href="{{ route('akun.edit', $d->id) }}" class="btn btn-success btn-sm">Edit</a>
                <button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button>
              </form>
            </td>
          </tr>
        @endforeach
      </table>
      {{ $user->links() }}
    </div>
  </div>
@endsection