Toko-Online-Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
  return view('welcome');
});

Route::get('/clear-cache', function () {
  Artisan::call('config:clear');
  Artisan::call('cache:clear');
  Artisan::call('config:cache');
  return 'DONE';
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
  Route::middleware(['role'])->group(function () {
    Route::resource('/merek', 'MerekController');
    Route::resource('/order', 'OrderController');
    Route::get('/order/tampil_cancel', 'OrderController@tampil_cancel')->name('order.tampil_cancel');
    Route::get('/order/tampil_bayar', 'OrderController@tampil_bayar')->name('order.tampil_bayar');
    Route::get('/order/tampil_pending', 'OrderController@tampil_pending')->name('order.tampil_pending');
    Route::resource('/akun', 'AkunController');
    Route::resource('/mobil', 'MobilController');
    Route::get('/create/mobil', 'MobilController@create')->name('create.mobil');
    Route::get('/mobil/tampil_hapus', 'MobilController@tampil_hapus')->name('mobil.tampil_hapus');
    Route::get('/mobil/restore/{id}', 'MobilController@restore')->name('mobil.restore');
    Route::delete('/mobil/kill/{id}', 'MobilController@kill')->name('mobil.kill');
  });

  Route::get('/', 'MobilController@home')->name('home');
  Route::get('/home', 'MobilController@home')->name('home');
  Route::get('/favorite', 'MobilController@favorite')->name('favorite');
  Route::get('/like/{id}', 'MobilController@like')->name('like');
  Route::get('/unlike/{id}', 'MobilController@unlike')->name('unlike');
  Route::get('/cart', 'MobilController@cart')->name('cart');
  Route::get('/add-to-cart/{id}', 'MobilController@addToCart')->name('add-to-cart');
  Route::get('/mobil/{id}', 'MobilController@show')->name('mobil.show');
  Route::get('/profil/{id}', 'AkunController@profil')->name('profil');
  Route::get('/edit_profil/{id}', 'AkunController@edit_profil')->name('edit_profil');
  Route::post('/akun/simpan/{id}', 'AkunController@simpan')->name('akun.simpan');
  Route::patch('/update_cart', 'MobilController@update_cart')->name('update_cart');
  Route::delete('/remove', 'MobilController@remove')->name('remove');
  Route::delete('/order/{id}', 'OrderController@destroy')->name('order.destroy');
  Route::get('/cekout', 'MobilController@cekout')->name('cekout');
  Route::get('/category/{id}', 'MobilController@category')->name('category');
  Route::get('/history', 'OrderController@history')->name('history');
  Route::get('/pembayaran/success', 'OrderController@success')->name('pembayaran.success');
  Route::get('/pembayaran/{id}', 'OrderController@pembayaran')->name('pembayaran');
  Route::patch('/proses_pembayaran/{id}', 'OrderController@proses_pembayaran')->name('proses_pembayaran');
  Route::post('/proses_cekout/{id}', 'MobilController@proses_cekout')->name('proses_cekout');
});

Toko-Online-Laravel/resources/views/template_backend/footer.blade.php
<!-- Footer Start-->
<div class="footer-copyright-area">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="footer-copy-right">
          <p>Copyright &copy; @if(date('Y') == '2019') {{ date('Y') }} @else 2019 - {{ date('Y') }} @endif All rights reserved <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://github.com/adhiariyadi/" target="_blank">Adhi Ariyadi</a>.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer End-->

<!-- jquery
============================================ -->
<script src="{{ asset('admin/js/vendor/jquery-1.11.3.min.js') }}"></script>
<!-- bootstrap JS
============================================ -->
<script src="{{ asset('admin/js/bootstrap.min.js') }}"></script>
<!-- meanmenu JS
============================================ -->
<script src="{{ asset('admin/js/jquery.meanmenu.js') }}"></script>
<!-- mCustomScrollbar JS
============================================ -->
<script src="{{ asset('admin/js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
<!-- sticky JS
============================================ -->
<script src="{{ asset('admin/js/jquery.sticky.js') }}"></script>
<!-- scrollUp JS
============================================ -->
<script src="{{ asset('admin/js/jquery.scrollUp.min.js') }}"></script>
<!-- counterup JS
============================================ -->
<script src="{{ asset('admin/js/counterup/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('admin/js/counterup/waypoints.min.js') }}"></script>
<script src="{{ asset('admin/js/counterup/counterup-active.js') }}"></script>
<!-- peity JS
============================================ -->
<script src="{{ asset('admin/js/peity/jquery.peity.min.js') }}"></script>
<script src="{{ asset('admin/js/peity/peity-active.js') }}"></script>
<!-- sparkline JS
============================================ -->
<script src="{{ asset('admin/js/sparkline/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('admin/js/sparkline/sparkline-active.js') }}"></script>
<!-- flot JS
============================================ -->
<script src="{{ asset('admin/js/flot/Chart.min.js') }}"></script>
<script src="{{ asset('admin/js/flot/flot-active.js') }}"></script>
<!-- map JS
============================================ -->
<script src="{{ asset('admin/js/map/raphael.min.js') }}"></script>
<script src="{{ asset('admin/js/map/jquery.mapael.js') }}"></script>
<script src="{{ asset('admin/js/map/france_departments.js') }}"></script>
<script src="{{ asset('admin/js/map/world_countries.js') }}"></script>
<script src="{{ asset('admin/js/map/usa_states.js') }}"></script>
<script src="{{ asset('admin/js/map/map-active.js') }}"></script>
<!-- data table JS
============================================ -->
<script src="{{ asset('admin/js/data-table/bootstrap-table.js') }}"></script>
<script src="{{ asset('admin/js/data-table/tableExport.js') }}"></script>
<script src="{{ asset('admin/js/data-table/data-table-active.js') }}"></script>
<script src="{{ asset('admin/js/data-table/bootstrap-table-editable.js') }}"></script>
<script src="{{ asset('admin/js/data-table/bootstrap-editable.js') }}"></script>
<script src="{{ asset('admin/js/data-table/bootstrap-table-resizable.js') }}"></script>
<script src="{{ asset('admin/js/data-table/colResizable-1.5.source.js') }}"></script>
<script src="{{ asset('admin/js/data-table/bootstrap-table-export.js') }}"></script>
<!-- modal JS
============================================ -->
<script src="{{ asset('admin/js/modal-active.js') }}"></script>
<!-- touchspin JS
============================================ -->
<script src="{{ asset('admin/js/touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>
<script src="{{ asset('admin/js/touchspin/touchspin-active.js') }}"></script>
<!-- colorpicker JS
============================================ -->
<script src="{{ asset('admin/js/colorpicker/jquery.spectrum.min.js') }}"></script>
<script src="{{ asset('admin/js/colorpicker/color-picker-active.js') }}"></script>
<!-- datapicker JS
============================================ -->
<script src="{{ asset('admin/js/datapicker/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('admin/js/datapicker/datepicker-active.js') }}"></script>
<!-- input-mask JS
============================================ -->
<script src="{{ asset('admin/js/input-mask/jasny-bootstrap.min.js') }}"></script>
<!-- chosen JS
============================================ -->
<script src="{{ asset('admin/js/chosen/chosen.jquery.js') }}"></script>
<script src="{{ asset('admin/js/chosen/chosen-active.js') }}"></script>
<!-- ionRangeSlider JS
============================================ -->
<script src="{{ asset('admin/js/ionRangeSlider/ion.rangeSlider.min.js') }}"></script>
<script src="{{ asset('admin/js/ionRangeSlider/ion.rangeSlider.active.js') }}"></script>
<!-- rangle-slider JS
============================================ -->
<script src="{{ asset('admin/js/rangle-slider/jquery-ui-1.10.4.custom.min.js') }}"></script>
<script src="{{ asset('admin/js/rangle-slider/jquery-ui-touch-punch.min.js') }}"></script>
<script src="{{ asset('admin/js/rangle-slider/rangle-active.js') }}"></script>
<!-- knob JS
============================================ -->
<script src="{{ asset('admin/js/knob/jquery.knob.js') }}"></script>
<script src="{{ asset('admin/js/knob/knob-active.js') }}"></script>
<!-- select2 JS
============================================ -->
<script src="{{ asset('admin/js/select2/select2.full.min.js') }}"></script>
<script src="{{ asset('admin/js/select2/select2-active.js') }}"></script>
<!-- main JS
============================================ -->
<script src="{{ asset('admin/js/main.js') }}"></script>
<script src="{{ asset('user/js/main.js') }}"></script>

</body>

</html>

Toko-Online-Laravel/resources/views/template_backend/home.blade.php
<!doctype html>
<html class="no-js" lang="en">

<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#000000">
  <meta name="description" content="Web site created using create-react-app">
  <link rel="apple-touch-icon" href="{{ asset('logo192.png') }}">
  <link rel="manifest" href="{{ asset('manifest.json') }}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Laravel &mdash; CRUD</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Google Fonts
	============================================ -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet">
  <!-- Bootstrap CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/bootstrap.min.css') }}">
  <!-- Bootstrap CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/font-awesome.min.css') }}">
  <!-- adminpro icon CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/adminpro-custon-icon.css') }}">
  <!-- meanmenu icon CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/meanmenu.min.css') }}">
  <!-- mCustomScrollbar CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/jquery.mCustomScrollbar.min.css') }}">
  <!-- animate CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/animate.css') }}">
  <!-- data-table CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/data-table/bootstrap-table.css') }}">
  <link rel="stylesheet" href="{{ asset('admin/css/data-table/bootstrap-editable.css') }}">
  <!-- normalize CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/normalize.css') }}">
  <!-- charts C3 CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/c3.min.css') }}">
  <!-- forms CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/form/all-type-forms.css') }}">
  <link rel="stylesheet" href="{{ asset('admin/css/form/themesaller-forms.css') }}">
  <!-- modals CSS
  ============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/modals.css') }}">
  <!-- touchspin CSS
  ============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/touchspin/jquery.bootstrap-touchspin.min.css') }}">
  <!-- datapicker CSS
  ============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/datapicker/datepicker3.css') }}">
  <!-- colorpicker CSS
  ============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/colorpicker/colorpicker.css') }}">
  <!-- select2 CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/select2/select2.min.css') }}">
  <!-- chosen CSS
  ============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/chosen/bootstrap-chosen.css') }}">
  <!-- ionRangeSlider CSS
  ============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/ionRangeSlider/ion.rangeSlider.css') }}">
  <link rel="stylesheet" href="{{ asset('admin/css/ionRangeSlider/ion.rangeSlider.skinFlat.css') }}">
  <!-- style CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/style.css') }}">
	<link rel="stylesheet" href="{{ asset('user/css/animate.css') }}">
	<link rel="stylesheet" href="{{ asset('user/css/style.css') }}">
  <!-- responsive CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/responsive.css') }}">
  <!-- responsive CSS
	============================================ -->
  <link rel="stylesheet" href="{{ asset('admin/css/responsive.css') }}">
  <!-- modernizr JS
	============================================ -->
  <script src="{{ asset('admin/js/vendor/modernizr-2.8.3.min.js') }}"></script>
</head>

<body class="materialdesign">
  <!--[if lt IE 8]>
          <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
      <![endif]-->

	<!-- Page Preloder -->
	{{-- <div id="preloder">
		<div class="loader"></div>
	</div> --}}

  <!-- Header top area start-->
  <div class="wrapper-pro">
    @include('template_backend.sidebar')
    <div class="content-inner-all">
      @include('template_backend.navbar')
    <!-- Header top area end-->
          <!-- Breadcome start-->
          <div class="breadcome-area mg-b-30 small-dn">
              <div class="container-fluid">
                  <div class="row">
                      <div class="col-lg-12">
                          <div class="breadcome-list map-mg-t-40-gl shadow-reset">
                              <div class="row">
                                  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            										<div class="breadcome-heading">
            											<form role="search" class="">
            												<input type="text" placeholder="Search..." class="form-control">
            												<a href=""><i class="fa fa-search"></i></a>
            											</form>
            										</div>
                                  </div>
                                  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                      <ul class="breadcome-menu">
                                          <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                          </li>
                                          <li><span class="bread-blod">@yield('halaman')</span>
                                          </li>
                                      </ul>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!-- Breadcome End-->
          @include('template_backend.mobile')
          <!-- welcome Project, sale area start-->
          <div class="welcome-adminpro-area">
            <div class="container-fluid">
              <div class="row">
                @yield('content')
              </div>
            </div>
          </div>
      </div>
  </div>

@include('template_backend.footer')

Toko-Online-Laravel/resources/views/template_backend/mobile.blade.php
<!-- Mobile Menu start -->
<div class="mobile-menu-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="mobile-menu">
          <nav id="dropdown">
            <ul class="mobile-menu-nav">
              <li class="nav-item"><a href="/" class="nav-link dropdown-toggle">Home <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a></li>
              <li><a data-toggle="collapse" data-target="#demo" href="#">Order <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                <ul id="demo" class="collapse dropdown-header-top">
                  <li><a href="{{ route('order.index') }}">List Order</a></li>
                  <li><a href="{{ route('order.tampil_cancel') }}">List Batal Order</a></li>
                </ul>
              </li>
              <li><a data-toggle="collapse" data-target="#demo" href="#">Mobil <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a>
                <ul id="demo" class="collapse dropdown-header-top">
                  <li><a href="{{ route('mobil.index') }}">List Mobil</a></li>
                  <li><a href="{{ route('mobil.tampil_hapus') }}">List Mobil Dihapus</a></li>
                </ul>
              </li>
              <li class="nav-item"><a href="{{ route('merek.index') }}" class="nav-link dropdown-toggle">Merek <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a></li>
              <li class="nav-item"><a href="{{ route('akun.index') }}" class="nav-link dropdown-toggle">Akun <span class="admin-project-icon adminpro-icon adminpro-down-arrow"></span></a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Mobile Menu end -->
<!-- Breadcome start-->
<div class="breadcome-area des-none">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="breadcome-list map-mg-t-40-gl shadow-reset">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <div class="breadcome-heading">
                <form role="search" class="">
                  <input type="text" placeholder="Search..." class="form-control">
                  <a href=""><i class="fa fa-search"></i></a>
                </form>
              </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <ul class="breadcome-menu">
                <li><a href="#">Home</a> <span class="bread-slash">/</span></li>
                <li><span class="bread-blod">@yield('halaman')</span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Breadcome End-->

Toko-Online-Laravel/resources/views/template_backend/navbar.blade.php
<div class="header-top-area">
  <div class="fixed-header-top">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-1 col-md-6 col-sm-6 col-xs-8">
          <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
            <i class="fa fa-bars"></i>
          </button>
        </div>
        <div class="col-lg-11 col-md-6 col-sm-6 col-xs-4">
          <div class="header-right-info">
            <ul class="nav navbar-nav mai-top-nav header-right-menu">
              <li class="nav-item">
                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                  <span class="adminpro-icon adminpro-user-rounded header-riht-inf"></span>
                  <span class="admin-name">{{ Auth::user()->name }}</span>
                  <span class="author-project-icon adminpro-icon adminpro-down-arrow"></span>
                </a>
                <ul role="menu" class="dropdown-header-top author-log dropdown-menu animated flipInX">
                  <li><a href="{{ route('profil', Auth::user()->id) }}"><span class="adminpro-icon adminpro-user-rounded author-log-ic"></span>My Profile</a></li>
                  <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><span class="adminpro-icon adminpro-locked author-log-ic"></span>{{ __('Logout') }}</a></li>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

Toko-Online-Laravel/resources/views/template_backend/sidebar.blade.php
<div class="left-sidebar-pro">
  <nav id="sidebar">
    <div class="sidebar-header">
      <a href="{{ route('profil', Auth::user()->id) }}">
        @if ( Auth::user()->gambar )
          <img style="width: 100px; height:100px;" class="rounded-circle img-thumbnail" src="{{ asset(Auth::user()->gambar) }}" alt="" />
        @else
          <img class="rounded-circle img-thumbnail" src="{{ asset('admin/img/message/1.jpg') }}" alt="" />
        @endif
      </a>
      <h3>{{ Auth::user()->name }}</h3>
      <p style="text-transform: uppercase;">
        @if ( Auth::user()->pekerjaan )
          {{ Auth::user()->pekerjaan }}
        @else
          N/A
        @endif
      </p>
      <strong>DG</strong>
    </div>
    <div class="left-custom-menu-adp-wrap">
      <ul class="nav navbar-nav left-sidebar-menu-pro">
        <li class="nav-item"><a href="/" class="nav-link dropdown-toggle"><i class="fa big-icon fa-home"></i> <span class="mini-dn">Home</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a></li>
        <li class="nav-item">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><i class="fa big-icon fa-shopping-bag"></i> <span class="mini-dn">Order</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a>
          <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
            <a href="{{ route('order.index') }}" class="dropdown-item">List Order</a>
            <a href="{{ route('order.tampil_cancel') }}" class="dropdown-item">List Batal Order</a>
          </div>
        </li>
        <li class="nav-item">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><i class="fa big-icon fa-car"></i> <span class="mini-dn">Mobil</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a>
          <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
            <a href="{{ route('mobil.index') }}" class="dropdown-item">List Mobil</a>
            <a href="{{ route('mobil.tampil_hapus') }}" class="dropdown-item">List Mobil Dihapus</a>
          </div>
        </li>
        <li class="nav-item"><a href="{{ route('merek.index') }}" class="nav-link dropdown-toggle"><i class="fa big-icon fa-clipboard"></i> <span class="mini-dn">Merek</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a></li>
        <li class="nav-item"><a href="{{ route('akun.index') }}" class="nav-link dropdown-toggle"><i class="fa big-icon fa-user"></i> <span class="mini-dn">Akun</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a></li>
      </ul>
    </div>
  </nav>
</div>