Toko-Online-Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
  return view('welcome');
});

Route::get('/clear-cache', function () {
  Artisan::call('config:clear');
  Artisan::call('cache:clear');
  Artisan::call('config:cache');
  return 'DONE';
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
  Route::middleware(['role'])->group(function () {
    Route::resource('/merek', 'MerekController');
    Route::resource('/order', 'OrderController');
    Route::get('/order/tampil_cancel', 'OrderController@tampil_cancel')->name('order.tampil_cancel');
    Route::get('/order/tampil_bayar', 'OrderController@tampil_bayar')->name('order.tampil_bayar');
    Route::get('/order/tampil_pending', 'OrderController@tampil_pending')->name('order.tampil_pending');
    Route::resource('/akun', 'AkunController');
    Route::resource('/mobil', 'MobilController');
    Route::get('/create/mobil', 'MobilController@create')->name('create.mobil');
    Route::get('/mobil/tampil_hapus', 'MobilController@tampil_hapus')->name('mobil.tampil_hapus');
    Route::get('/mobil/restore/{id}', 'MobilController@restore')->name('mobil.restore');
    Route::delete('/mobil/kill/{id}', 'MobilController@kill')->name('mobil.kill');
  });

  Route::get('/', 'MobilController@home')->name('home');
  Route::get('/home', 'MobilController@home')->name('home');
  Route::get('/favorite', 'MobilController@favorite')->name('favorite');
  Route::get('/like/{id}', 'MobilController@like')->name('like');
  Route::get('/unlike/{id}', 'MobilController@unlike')->name('unlike');
  Route::get('/cart', 'MobilController@cart')->name('cart');
  Route::get('/add-to-cart/{id}', 'MobilController@addToCart')->name('add-to-cart');
  Route::get('/mobil/{id}', 'MobilController@show')->name('mobil.show');
  Route::get('/profil/{id}', 'AkunController@profil')->name('profil');
  Route::get('/edit_profil/{id}', 'AkunController@edit_profil')->name('edit_profil');
  Route::post('/akun/simpan/{id}', 'AkunController@simpan')->name('akun.simpan');
  Route::patch('/update_cart', 'MobilController@update_cart')->name('update_cart');
  Route::delete('/remove', 'MobilController@remove')->name('remove');
  Route::delete('/order/{id}', 'OrderController@destroy')->name('order.destroy');
  Route::get('/cekout', 'MobilController@cekout')->name('cekout');
  Route::get('/category/{id}', 'MobilController@category')->name('category');
  Route::get('/history', 'OrderController@history')->name('history');
  Route::get('/pembayaran/success', 'OrderController@success')->name('pembayaran.success');
  Route::get('/pembayaran/{id}', 'OrderController@pembayaran')->name('pembayaran');
  Route::patch('/proses_pembayaran/{id}', 'OrderController@proses_pembayaran')->name('proses_pembayaran');
  Route::post('/proses_cekout/{id}', 'MobilController@proses_cekout')->name('proses_cekout');
});

Toko-Online-Laravel/app/Merek.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Merek extends Model
{
    protected $fillable = ['name'];

    public function jumlah($id)
    {
        $mobil = Mobil::where('merek_id', $id)->count();
        return $mobil;
    }

    protected $table = 'merek';
}

Toko-Online-Laravel/app/Http/Controllers/MerekController.php
<?php

namespace App\Http\Controllers;

use App\Merek;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class MerekController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $merek = Merek::paginate(10);
        return view('admin.merek.index', compact('merek'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.merek.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|min:3'
        ]);

        $merek = Merek::create([
          'name' => $request->name,
        ]);

        return redirect()->back()->with('success', 'Merek Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $merek = Merek::findorfail($id);
        return view('admin.merek.edit', compact('merek'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
        'name' => 'required|min:3'
      ]);

      $merek_data = [
        'name' => $request->name,
      ];

      Merek::whereId($id)->update($merek_data);

      return redirect()->route('merek.index')->with('success', 'Merek Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $merek = Merek::findorfail($id);
        $merek->delete();

        return redirect()->back()->with('success', 'Merek Berhasil Dihapus');
    }
}

Toko-Online-Laravel/resources/views/admin/merek/create.blade.php
@extends('template_backend.home')
@section('halaman', 'Tambah Merek')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <form action="{{ route('merek.store') }}" method="post">
        @csrf
        <div class="form-group">
          <label>Merek Mobil</label>
          <input type="text" class="form-control" name="name" autocomplete="off">
        </div>

        <div class="form-group">
          <button class="btn btn-primary btn-block">Simpan Merek</button>
        </div>
      </form>
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/merek/edit.blade.php
@extends('template_backend.home')
@section('halaman', 'Edit Merek')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <form action="{{ route('merek.update', $merek->id) }}" method="post">
        @csrf
        @method('patch')
        <div class="form-group">
          <label>Merek Mobil</label>
          <input type="text" class="form-control" value="{{ $merek->name }}" name="name" autocomplete="off">
        </div>

        <div class="form-group">
          <button class="btn btn-primary btn-block">Update Merek</button>
        </div>
      </form>
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/merek/index.blade.php
@extends('template_backend.home')
@section('halaman', 'List Merek')
@section('content')
  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <a href="{{ route('merek.create') }}" class="btn btn-primary btn-sm">Tambah Merek</a><br><br>
      <table class="table table-striped table-hover table-sm table-bordered">
        <tr>
          <th>No</th>
          <th>Nama Merek</th>
          <th>Action</th>
        </tr>
        @foreach ($merek as $result => $d)
          <tr>
            <td>{{ $result + $merek->firstitem() }}</td>
            <td>{{ $d->name }}</td>
            <td>
              <form action="{{ route('merek.destroy', $d->id) }}" method="post">
                @csrf
                @method('delete')
                <a href="{{ route('merek.edit', $d->id) }}" class="btn btn-success btn-sm">Edit</a>
                <button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button>
              </form>
            </td>
          </tr>
        @endforeach
      </table>
      {{ $merek->links() }}
    </div>
  </div>
@endsection