Toko-Online-Laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
  return view('welcome');
});

Route::get('/clear-cache', function () {
  Artisan::call('config:clear');
  Artisan::call('cache:clear');
  Artisan::call('config:cache');
  return 'DONE';
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
  Route::middleware(['role'])->group(function () {
    Route::resource('/merek', 'MerekController');
    Route::resource('/order', 'OrderController');
    Route::get('/order/tampil_cancel', 'OrderController@tampil_cancel')->name('order.tampil_cancel');
    Route::get('/order/tampil_bayar', 'OrderController@tampil_bayar')->name('order.tampil_bayar');
    Route::get('/order/tampil_pending', 'OrderController@tampil_pending')->name('order.tampil_pending');
    Route::resource('/akun', 'AkunController');
    Route::resource('/mobil', 'MobilController');
    Route::get('/create/mobil', 'MobilController@create')->name('create.mobil');
    Route::get('/mobil/tampil_hapus', 'MobilController@tampil_hapus')->name('mobil.tampil_hapus');
    Route::get('/mobil/restore/{id}', 'MobilController@restore')->name('mobil.restore');
    Route::delete('/mobil/kill/{id}', 'MobilController@kill')->name('mobil.kill');
  });

  Route::get('/', 'MobilController@home')->name('home');
  Route::get('/home', 'MobilController@home')->name('home');
  Route::get('/favorite', 'MobilController@favorite')->name('favorite');
  Route::get('/like/{id}', 'MobilController@like')->name('like');
  Route::get('/unlike/{id}', 'MobilController@unlike')->name('unlike');
  Route::get('/cart', 'MobilController@cart')->name('cart');
  Route::get('/add-to-cart/{id}', 'MobilController@addToCart')->name('add-to-cart');
  Route::get('/mobil/{id}', 'MobilController@show')->name('mobil.show');
  Route::get('/profil/{id}', 'AkunController@profil')->name('profil');
  Route::get('/edit_profil/{id}', 'AkunController@edit_profil')->name('edit_profil');
  Route::post('/akun/simpan/{id}', 'AkunController@simpan')->name('akun.simpan');
  Route::patch('/update_cart', 'MobilController@update_cart')->name('update_cart');
  Route::delete('/remove', 'MobilController@remove')->name('remove');
  Route::delete('/order/{id}', 'OrderController@destroy')->name('order.destroy');
  Route::get('/cekout', 'MobilController@cekout')->name('cekout');
  Route::get('/category/{id}', 'MobilController@category')->name('category');
  Route::get('/history', 'OrderController@history')->name('history');
  Route::get('/pembayaran/success', 'OrderController@success')->name('pembayaran.success');
  Route::get('/pembayaran/{id}', 'OrderController@pembayaran')->name('pembayaran');
  Route::patch('/proses_pembayaran/{id}', 'OrderController@proses_pembayaran')->name('proses_pembayaran');
  Route::post('/proses_cekout/{id}', 'MobilController@proses_cekout')->name('proses_cekout');
});

Toko-Online-Laravel/app/Mobil.php
<?php

namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Mobil extends Model
{
  use SoftDeletes;

  protected $fillable = ['merek_id', 'type', 'price', 'gambar', 'stock'];

  public function merek()
  {
    return $this->belongsTo('App\Merek');
  }

  public function like($id)
  {
    $like = Favorite::where('user_id', Auth::user()->id)->where('mobil_id', $id)->first();
    return $like;
  }

  protected $table = 'mobil';
}

Toko-Online-Laravel/app/Http/Controllers/MobilController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Mobil;
use App\Merek;
use App\Order;
use App\Favorite;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Session;

class MobilController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $mobil = Mobil::paginate(10);
    return view('admin.mobil.index', compact('mobil'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $merek = Merek::all();
    return view('admin.mobil.create', compact('merek'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'type' => 'required',
      'price' => 'required',
      'gambar' => 'required'
    ]);

    $gambar = $request->gambar;
    $new_gambar = date('Ymdhis') . "_" . $gambar->getClientOriginalName();

    Mobil::create([
      'merek_id' => $request->merek_id,
      'type' => $request->type,
      'price' => $request->price,
      'gambar' => 'uploads/mobil/' . $new_gambar,
    ]);

    $gambar->move('uploads/mobil/', $new_gambar);

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Disimpan');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    $mobil = Mobil::findorfail($id);
    $merek = Merek::all();
    $produk = Mobil::where('merek_id', $mobil->merek_id)->orderBy('created_at', 'DESC')->limit(5)->get();
    return view('user.show', compact('mobil', 'merek', 'produk'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $mobil = Mobil::findorfail($id);
    $merek = Merek::all();
    return view('admin.mobil.edit', compact('mobil', 'merek'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $this->validate($request, [
      'price' => 'required',
      'type' => 'required'
    ]);

    $mobil = Mobil::findorfail($id);

    if ($request->gambar == true) {
      $gambar = $request->gambar;
      $new_gambar = date('Ymdhis') . "_" . $gambar->getClientOriginalName();
      $gambar->move('uploads/mobil/', $new_gambar);
      $mobil_data = [
        'merek_id' => $request->merek_id,
        'type' => $request->type,
        'price' => $request->price,
        'gambar' => 'uploads/mobil/' . $new_gambar,
      ];
    } else {
      $mobil_data = [
        'merek_id' => $request->merek_id,
        'price' => $request->price,
        'type' => $request->type,
      ];
    }

    $mobil->update($mobil_data);

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Diupdate');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $mobil = Mobil::findorfail($id);
    $mobil->delete();

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Dihapus (Silahkan cek trashed mobil)');
  }

  public function new()
  {
    $mobil = Mobil::paginate(10);
    $merek = Merek::all();
    return view('admin.mobil.index', compact('mobil', 'merek'));
  }

  public function tampil_hapus()
  {
    $mobil = Mobil::onlyTrashed()->paginate(10);
    return view('admin.mobil.tampil_hapus', compact('mobil'));
  }

  public function restore($id)
  {
    $mobil = Mobil::withTrashed()->where('id', $id)->first();
    $mobil->restore();

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Direstore (Silahkan cek list mobil)');
  }

  public function kill($id)
  {
    $mobil = Mobil::withTrashed()->where('id', $id)->first();
    $mobil->forceDelete();

    return redirect()->back()->with('success', 'Postingan Anda Berhasil Dihapus Secara Permanent');
  }

  public function home()
  {
    $mobil = Mobil::orderBy('created_at', 'DESC')->get();
    $car = Mobil::orderBy('created_at', 'DESC')->limit(5)->get();
    $merek = Merek::all();
    return view('user.index', compact('mobil', 'car', 'merek'));
  }

  public function cart()
  {
    $cart = session()->get('cart');
    $mobil = Mobil::paginate(10);

    $this->item['chart'] = $cart;
    $this->item['mobil'] = $mobil;

    $merek = Merek::all();
    $produk = Mobil::orderBy('created_at', 'DESC')->limit(4)->get();

    return view('user.cart', compact('merek', 'produk'));
  }

  public function addToCart($id)
  {
    $mobil = Mobil::findorfail($id);

    if (!$mobil) {
      abort(404);
    }

    $cart = session()->get('cart');

    if (isset($cart[$id])) {
      $cart[$id]['quantity']++;
      session()->put('cart', $cart);
      return redirect()->back()->with('success', 'Product added to cart successfully!');
    }

    $cart[$id] = [
      "mobil_id" => $mobil->id,
      "name" => $mobil->type,
      "brand" => $mobil->merek->name,
      "quantity" => 1,
      "price" => $mobil->price,
      "photo" => $mobil->gambar,
    ];

    session()->put('cart', $cart);
    return redirect()->back()->with('success', 'Product added to cart successfully!');
  }

  public function update_cart(Request $request)
  {
    if ($request->id && $request->quantity) {
      $cart = session()->get('cart');
      $cart[$request->id]['quantity'] = $request->quantity;
      session()->put('cart', $cart);
      session()->flash('success', 'Cart updated successfully!');
    }
  }

  public function remove(Request $request)
  {
    if ($request->id) {
      $cart = session()->get('cart');

      if (isset($cart[$request->id])) {
        unset($cart[$request->id]);

        session()->put('cart', $cart);
        Session::flash('success', 'Berhasil menghapus product');
      }
    }
  }

  public function cekout()
  {
    $cart = session()->get('cart');
    $mobil = Mobil::paginate(10);

    $this->item['chart'] = $cart;
    $this->item['mobil'] = $mobil;

    $merek = Merek::all();

    return view('user.cekout', compact('merek'));
  }

  public function proses_cekout(Request $request, $id)
  {
    $user = User::findorfail($id);

    $user_data = [
      'address' => $request->address,
      'kelurahan' => $request->kelurahan,
      'kabupaten' => $request->kabupaten,
      'kecamatan' => $request->kecamatan,
      'provinsi' => $request->provinsi,
      'kode_pos' => $request->kode_pos,
      'telepon' => $request->telepon,
    ];

    $user->update($user_data);

    $cart = session()->get('cart');

    foreach ($cart as $details) {
      Order::create([
        'user_id' => $id,
        'mobil_id' => $details['mobil_id'],
        'quantity' => $details['quantity'],
        'total' => $details['price'] * $details['quantity'],
        'payment_status' => 'Belum Dibayar',
      ]);
    }

    $request->session()->forget('cart');

    $order = Order::orderBy('created_at', 'DESC')->where('user_id', $id)->first();

    return redirect()->route('pembayaran', $order->id)->with('success', 'Pembelian Berhasil Silahkan Melakukan Pembayaran Melalui Payment Yang Anda Pilih');
  }

  public function category($id)
  {
    $judul = Merek::findorfail($id);
    $mobil = Mobil::orderBy('created_at', 'DESC')->where('merek_id', $id)->paginate(12);
    $new = Mobil::orderBy('created_at', 'DESC')->first();
    $merek = Merek::all();

    return view('user.category', compact('judul', 'mobil', 'new', 'merek'));
  }

  public function like($id)
  {
    Favorite::create([
      'user_id' => Auth::user()->id,
      'mobil_id' => $id,
    ]);

    return redirect()->back()->with('success', 'Product added to favorite successfully!');
  }

  public function unlike($id)
  {
    $like = Favorite::where('user_id', Auth::user()->id)->where('mobil_id', $id)->first();
    $like->delete();

    return redirect()->back()->with('success', 'Product cancel to favorite successfully!');
  }

  public function favorite()
  {
    $like = Favorite::where('user_id', Auth::user()->id)->get();
    $new = Mobil::orderBy('created_at', 'DESC')->first();
    $merek = Merek::all();

    return view('user.favorite', compact('like', 'new', 'merek'));
  }
}

Toko-Online-Laravel/resources/views/admin/mobil/create.blade.php
@extends('template_backend.home')
@section('halaman', 'Tambah Mobil')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <form action="{{ route('mobil.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label>Merek</label>
          <div class="chosen-select-single mg-b-20">
            <select class="select2_demo_3 form-control" name="merek_id">
              <option value="" holder>Pilih Merek</option>
              @foreach ($merek as $d)
                <option value="{{ $d->id }}">{{ $d->name }}</option>
              @endforeach
            </select>
          </div>
        </div>
        <div class="form-group">
          <label>Type</label>
          <input type="text" class="form-control" name="type" placeholder="Type Mobil" autocomplete="off">
        </div>
        <div class="form-group">
          <label>Price</label>
          <input type="number" class="form-control" name="price" placeholder="Price Mobil">
        </div>
        <div class="form-group">
          <label for="exampleInputFile">Foto Mobil</label>
          <div class="file-upload-inner ts-forms">
              <div class="input prepend-big-btn">
                  <label class="icon-right" for="prepend-big-btn">
                      <i class="fa fa-download"></i>
                  </label>
                  <div class="file-button">
                      Browse
                      <input type="file" name="gambar" onchange="document.getElementById('prepend-big-btn').value = this.value;">
                  </div>
                  <input type="text" id="prepend-big-btn" name="gambar" placeholder="no file selected">
              </div>
          </div>
        </div><br>

        <div class="form-group">
          <button class="btn btn-primary btn-block">Simpan Mobil</button>
        </div>
      </form>
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/mobil/edit.blade.php
@extends('template_backend.home')
@section('halaman', 'Edit Blog')
@section('content')
  @if (count($errors)>0)
    @foreach ($errors->all() as $error)
      <div class="alert alert-danger" role="alert">
        {{ $error }}
      </div>
    @endforeach
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <form action="{{ route('mobil.update', $mobil->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('patch')
        <div class="form-group">
          <label>Merek</label>
          <div class="chosen-select-single mg-b-20">
            <select class="select2_demo_3 form-control" name="merek_id">
              <option value="" holder>Pilih Merek</option>
              @foreach ($merek as $d)
                <option value="{{ $d->id }}"
                  @if ($mobil->merek_id == $d->id)
                    selected
                  @endif
                >{{ $d->name }}</option>
              @endforeach
            </select>
          </div>
        </div>
        <div class="form-group">
          <label>Type</label>
          <input type="text" class="form-control" value="{{ $mobil->type }}" name="type" placeholder="Type Mobil" autocomplete="off">
        </div>
        <div class="form-group">
          <label>Price</label>
            <input type="number" class="form-control" value="{{ $mobil->price }}" name="price" placeholder="Price Mobil">
        </div>
        <div class="form-group">
          <label for="exampleInputFile">Foto Mobil</label>
          <div class="file-upload-inner ts-forms">
              <div class="input prepend-big-btn">
                  <label class="icon-right" for="prepend-big-btn">
                      <i class="fa fa-download"></i>
                  </label>
                  <div class="file-button">
                      Browse
                      <input type="file" name="gambar" onchange="document.getElementById('prepend-big-btn').value = this.value;">
                  </div>
                  <input type="text" id="prepend-big-btn" name="gambar" placeholder="no file selected">
              </div>
          </div>
        </div><br>

        <div class="form-group">
          <button class="btn btn-primary btn-block">Update Mobil</button>
        </div>
      </form>
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/mobil/index.blade.php
@extends('template_backend.home')
@section('halaman', 'List Mobil')
@section('content')
  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <a href="{{ route('create.mobil') }}" class="btn btn-primary btn-sm">Tambah Mobil</a><br><br>
      <table class="table table-striped table-hover table-sm table-bordered">
        <tr>
          <th>No</th>
          <th>Merek Mobil</th>
          <th>Type Mobil</th>
          <th>price</th>
          <th>Thumbnail</th>
          <th>Action</th>
        </tr>
        @foreach ($mobil as $result => $d)
          <tr>
            <td>{{ $result + $mobil->firstitem() }}</td>
            <td>{{ $d->merek->name }}</td>
            <td>{{ $d->type }}</td>
            <td>$ {{ $d->price }}</td>
            <td>
              <img src="{{ asset( $d->gambar ) }}" class="img-fluid" width="100" alt="">
            </td>
            <td>
              <form action="{{ route('mobil.destroy', $d->id) }}" method="Mobil">
                @csrf
                @method('delete')
                <a href="{{ route('mobil.edit', $d->id) }}" class="btn btn-success btn-sm">Edit</a>
                <button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button>
              </form>
            </td>
          </tr>
        @endforeach
      </table>
      {{ $mobil->links() }}
    </div>
  </div>
@endsection

Toko-Online-Laravel/resources/views/admin/mobil/tampil_hapus.blade.php
@extends('template_backend.home')
@section('halaman', 'List Mobil Yang Dihapus')
@section('content')
  @if (Session::has('success'))
    <div class="alert alert-success" role="alert">
      {{ Session('success') }}
    </div>
  @endif

  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="welcome-wrapper shadow-reset res-mg-t mg-b-30">
      <a href="{{ route('mobil.create') }}" class="btn btn-primary btn-sm">Tambah Post</a><br><br>
      <table class="table table-striped table-hover table-sm table-bordered">
        <tr>
          <th>No</th>
          <th>Nama Post</th>
          <th>Kategori</th>
          <th>Daftar Tags</th>
          <th>Thumbnail</th>
          <th>Action</th>
        </tr>
        @foreach ($mobil as $result => $d)
          <tr>
            <td>{{ $result + $mobil->firstitem() }}</td>
            <td>{{ $d->merek->name }}</td>
            <td>{{ $d->type }}</td>
            <td>$ {{ $d->price }}</td>
            <td>
              <img src="{{ asset( $d->gambar ) }}" class="img-fluid" width="100" alt="">
            </td>
            <td>
              <form action="{{ route('mobil.kill', $d->id) }}" method="post">
                @csrf
                @method('delete')
                <a href="{{ route('mobil.restore', $d->id) }}" class="btn btn-success btn-sm">Restore</a>
                <button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button>
              </form>
            </td>
          </tr>
        @endforeach
      </table>
      {{ $mobil->links() }}
    </div>
  </div>
@endsection